# Generated by Django 2.2.6 on 2020-01-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0003_remove_author_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(related_name='fave', to='recipebox.Recipe'),
        ),
    ]
