# Generated by Django 2.2.6 on 2020-01-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0004_author_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='favorites',
        ),
    ]
