# Generated by Django 2.2.6 on 2020-01-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0005_remove_author_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(related_name='fave', to='recipebox.Recipe'),
        ),
    ]
