# Generated by Django 2.2.6 on 2020-01-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0006_author_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='fave', to='recipebox.Recipe'),
        ),
    ]
